export default (): string[] => [
    "fools around",
    "ponders the purrtun market",
    "evaluates you and your mistakes",
    "thinks carefully about",
    "eats",
    "disintegrates",
    "creates unimaginable horrors",
    "agrees with you",
    "does not care",
    "knows what you are",
    "knows the truth",
    "is consumed by her greed",
    "is consumed by his greed",
    "is consumed by their greed",
    "does not lose sleep over the opinions of bulgarians",
    "does not lose sleep over the thoughts of the french",
    "does not lose sleep over the judgement of the british",
    "sees past your illusionary mask",
    "opens a great portal",
    "is found dead in the morning",
];