export default (): string[] => [
  "ponders the purrtun market",
  "blows up your house",
  "evaluates you and your mistakes",
  "carefully plans his strategy",
  "carefully plans her strategy",
  "carefully plans their strategy",
  "eats",
  "disintegrates",
  "creates incomprehensible horrors",
  "agrees with this",
  "does not care",
  "knows what you are",
  "knows the truth",
  "is consumed by her greed",
  "is consumed by his greed",
  "is consumed by their greed",
  "does not lose sleep over the opinions of bulgarians",
  "is haunted by nightmares of bulgarians",
  "does not lose sleep over the thoughts of the french",
  "is haunted by nightmares of the french",
  "does not lose sleep over the judgement of the british",
  "is haunted by nightmares of the british",
  "does not lose sleep over the wisdom of the croatians",
  "is haunted by nightmares of croatians",
  "sees past your illusionary mask",
  "opens a great portal",
  "opens a mediocre portal",
  "is found dead in the morning",
  "watches diligently",
  "respects albania and its people",
];
